---
root: true

plugins:
  - babel

env:
  node: true
  browser: true

parser: "@babel/eslint-parser"

extends:
  - "airbnb-base"

rules:
  no-param-reassign: 0
#   no-console: 0
#   import/extensions: 0
#   consistent-return: 0